#!/bin/sh
## postflight
##
## https://github.com/philippe44/AirConnect
##
## Installs from: 
## https://github.com/philippe44/AirConnect/raw/master/bin/aircast-osx-multi
## https://github.com/philippe44/AirConnect/raw/master/bin/airupnp-osx-multi

loggedInUser=$( stat -f%Su /dev/console )

#
# Stop services if exist (without check)
#
sudo -u $loggedInUser launchctl unload -w /Library/LaunchAgents/com.aircast-osx-multi.plist 2> /dev/null
sudo -u $loggedInUser launchctl unload -w /Library/LaunchAgents/com.airupnp-osx-multi.plist 2> /dev/null

#
# Get latest executables
#
aircasturl="https://github.com/philippe44/AirConnect/raw/master/bin/aircast-osx-multi"
airupnpurl="https://github.com/philippe44/AirConnect/raw/master/bin/airupnp-osx-multi"

(cd /private/var/temp && curl -L -O $aircasturl)
(cd /private/var/temp && curl -L -O $airupnpurl)


if [ ! -d "/usr/local/bin" ] 
then
	mkdir -p -m 775 /usr/local/bin
	echo "/usr/local/bin does not exist. creating it..."
fi

cp /private/var/temp/aircast-osx-multi /usr/local/bin 
cp /private/var/temp/aircast-osx-multi /usr/local/bin 

#
# Set executables to executable
#
/bin/chmod +x "/usr/local/bin/aircast-osx-multi"
/bin/chmod +x "/usr/local/bin/airupnp-osx-multi"

#
# Create log files and set permissions.
#
touch /var/log/aircast.log
touch /var/log/airupnp.log

chmod 755 /var/log/aircast.log
chmod 755 /var/log/airupnp.log

#
# Start services
#
sudo -u $loggedInUser launchctl load -w /Library/LaunchAgents/com.aircast-osx-multi.plist
sudo -u $loggedInUser launchctl load -w /Library/LaunchAgents/com.airupnp-osx-multi.plist

#
# Check for permission to run exe in Security SIP and "allow" ?
#
#open -b com.apple.systempreferences /System/Library/PreferencePanes/Security.prefPane
#open x-apple.systempreferences:com.apple.preference.security?General

exit 0		## Success
exit 1		## Failure
